
package com.sip.business;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomNumberGenerator", targetNamespace = "http://business.sip.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RandomNumberGenerator {


    /**
     * 
     * @param upperBound
     * @param lowerBound
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://business.sip.com/RandomNumberGenerator/randomNumberRequest", output = "http://business.sip.com/RandomNumberGenerator/randomNumberResponse")
    public int randomNumber(
        @WebParam(name = "lowerBound", partName = "lowerBound")
        int lowerBound,
        @WebParam(name = "upperBound", partName = "upperBound")
        int upperBound);

}
